#pragma once

namespace BRDF { class BRDFClass; }
namespace GBuffer { class GBufferClass; }
namespace Shadow { class ShadowClass; }
namespace ZDepth { class ZDepthClass; }
namespace SSAO { class SSAOClass; }
namespace BlurFilter { class BlurFilterClass; }
namespace BlurFilter::CS { class BlurFilterCSClass; }
namespace Bloom { class BloomClass; }
namespace SSR { class SSRClass; }
namespace DepthOfField { class DepthOfFieldClass; }
namespace MotionBlur { class MotionBlurClass; }
namespace TemporalAA { class TemporalAAClass; }
namespace Debug { class DebugClass; }
namespace DXR_Shadow { class DXR_ShadowClass; }
namespace DXR_GeometryBuffer { class DXR_GeometryBufferClass; }
namespace RTAO { class RTAOClass; }
namespace GammaCorrection { class GammaCorrectionClass; }
namespace ToneMapping { class ToneMappingClass; }
namespace IrradianceMap { class IrradianceMapClass; }
namespace MipmapGenerator { class MipmapGeneratorClass; }
namespace Pixelation { class PixelationClass; }
namespace Sharpen { class SharpenClass; }
namespace GaussianFilter { class GaussianFilterClass; }
namespace RaytracedReflection { class RaytracedReflectionClass; }
namespace SVGF { class SVGFClass; }
namespace EquirectangularConverter { class EquirectangularConverterClass; }
namespace VolumetricLight { class VolumetricLightClass; }